/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BoardPublic model module.
 * @module model/BoardPublic
 * @version v1
 */
class BoardPublic {
    /**
     * @member {String} name
     * @type {String}
     */
    name;
    /**
     * @member {String} code
     * @type {String}
     */
    code;
    /**
     * @member {String} state
     * @type {String}
     */
    state;
    /**
     * @member {String} credentials_schema
     * @type {String}
     */
    credentials_schema;

    

    /**
     * Constructs a new <code>BoardPublic</code>.
     * @alias module:model/BoardPublic
     * @param name {String} 
     */
    constructor(name) { 
        
        BoardPublic.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>BoardPublic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BoardPublic} obj Optional instance to populate.
     * @return {module:model/BoardPublic} The populated <code>BoardPublic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BoardPublic();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('credentials_schema')) {
                obj['credentials_schema'] = ApiClient.convertToType(data['credentials_schema'], 'String');
            }
        }
        return obj;
    }
}



export default BoardPublic;

