/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CompanySubsidiary model module.
 * @module model/CompanySubsidiary
 * @version v1
 */
class CompanySubsidiary {
    /**
     * @member {String} id
     * @type {String}
     */
    id;
    /**
     * @member {Boolean} valid
     * @type {Boolean}
     */
    valid;
    /**
     * @member {Date} created
     * @type {Date}
     */
    created;
    /**
     * @member {Date} modified
     * @type {Date}
     */
    modified;
    /**
     * @member {String} ats_company_id
     * @type {String}
     */
    ats_company_id;
    /**
     * @member {Object} ats_credentials
     * @type {Object}
     */
    ats_credentials;
    /**
     * @member {String} name
     * @type {String}
     */
    name;
    /**
     * @member {String} street_address
     * @type {String}
     */
    street_address;
    /**
     * @member {String} postal_code
     * @type {String}
     */
    postal_code;
    /**
     * @member {String} career_site_url
     * @type {String}
     */
    career_site_url;
    /**
     * @member {String} fein
     * @type {String}
     */
    fein;
    /**
     * @member {String} sein
     * @type {String}
     */
    sein;
    /**
     * @member {String} uiid
     * @type {String}
     */
    uiid;
    /**
     * @member {CompanySubsidiary.StatusEnum} status
     * @type {CompanySubsidiary.StatusEnum}
     */
    status;
    /**
     * @member {String} letter_of_auth_docusign_envelope
     * @type {String}
     */
    letter_of_auth_docusign_envelope;
    /**
     * @member {String} ats
     * @type {String}
     */
    ats;
    /**
     * @member {String} hr_point_of_contact
     * @type {String}
     */
    hr_point_of_contact;
    /**
     * @member {String} compliance_admin_point_of_contact
     * @type {String}
     */
    compliance_admin_point_of_contact;
    /**
     * @member {String} company
     * @type {String}
     */
    company;

    

    /**
     * Constructs a new <code>CompanySubsidiary</code>.
     * @alias module:model/CompanySubsidiary
     * @param atsCompanyId {String} 
     * @param atsCredentials {Object} 
     */
    constructor(atsCompanyId, atsCredentials) { 
        
        CompanySubsidiary.initialize(this, atsCompanyId, atsCredentials);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, atsCompanyId, atsCredentials) { 
        obj['ats_company_id'] = atsCompanyId;
        obj['ats_credentials'] = atsCredentials;
    }

    /**
     * Constructs a <code>CompanySubsidiary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompanySubsidiary} obj Optional instance to populate.
     * @return {module:model/CompanySubsidiary} The populated <code>CompanySubsidiary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompanySubsidiary();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'Date');
            }
            if (data.hasOwnProperty('ats_company_id')) {
                obj['ats_company_id'] = ApiClient.convertToType(data['ats_company_id'], 'String');
            }
            if (data.hasOwnProperty('ats_credentials')) {
                obj['ats_credentials'] = ApiClient.convertToType(data['ats_credentials'], Object);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('street_address')) {
                obj['street_address'] = ApiClient.convertToType(data['street_address'], 'String');
            }
            if (data.hasOwnProperty('postal_code')) {
                obj['postal_code'] = ApiClient.convertToType(data['postal_code'], 'String');
            }
            if (data.hasOwnProperty('career_site_url')) {
                obj['career_site_url'] = ApiClient.convertToType(data['career_site_url'], 'String');
            }
            if (data.hasOwnProperty('fein')) {
                obj['fein'] = ApiClient.convertToType(data['fein'], 'String');
            }
            if (data.hasOwnProperty('sein')) {
                obj['sein'] = ApiClient.convertToType(data['sein'], 'String');
            }
            if (data.hasOwnProperty('uiid')) {
                obj['uiid'] = ApiClient.convertToType(data['uiid'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('letter_of_auth_docusign_envelope')) {
                obj['letter_of_auth_docusign_envelope'] = ApiClient.convertToType(data['letter_of_auth_docusign_envelope'], 'String');
            }
            if (data.hasOwnProperty('ats')) {
                obj['ats'] = ApiClient.convertToType(data['ats'], 'String');
            }
            if (data.hasOwnProperty('hr_point_of_contact')) {
                obj['hr_point_of_contact'] = ApiClient.convertToType(data['hr_point_of_contact'], 'String');
            }
            if (data.hasOwnProperty('compliance_admin_point_of_contact')) {
                obj['compliance_admin_point_of_contact'] = ApiClient.convertToType(data['compliance_admin_point_of_contact'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
        }
        return obj;
    }
}


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CompanySubsidiary['StatusEnum'] = {

    /**
     * value: "in_review"
     * @const
     */
    "in_review": "in_review",

    /**
     * value: "active"
     * @const
     */
    "active": "active",

    /**
     * value: "terminated"
     * @const
     */
    "terminated": "terminated"
};



export default CompanySubsidiary;

