/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ATS from './ATS';
import Set from './Set';

/**
 * The Company model module.
 * @module model/Company
 * @version v1
 */
class Company {
    /**
     * @member {ATS} ats
     * @type {ATS}
     */
    ats;
    /**
     * @member {String} ats_company_id
     * @type {String}
     */
    ats_company_id;
    /**
     * @member {Object} ats_credentials
     * @type {Object}
     */
    ats_credentials;
    /**
     * @member {String} career_site_url
     * @type {String}
     */
    career_site_url;
    /**
     * @member {String} compliance_admin_point_of_contact
     * @type {String}
     */
    compliance_admin_point_of_contact;
    /**
     * @member {String} contacts
     * @type {String}
     */
    contacts;
    /**
     * @member {Date} created
     * @type {Date}
     */
    created;
    /**
     * @member {Boolean} failed_audit_in_past_3_years
     * @type {Boolean}
     */
    failed_audit_in_past_3_years;
    /**
     * @member {String} fein
     * @type {String}
     */
    fein;
    /**
     * @member {String} hr_point_of_contact
     * @type {String}
     */
    hr_point_of_contact;
    /**
     * @member {String} id
     * @type {String}
     */
    id;
    /**
     * @member {Boolean} is_under_conciliation_agreements_with_ofccp
     * @type {Boolean}
     */
    is_under_conciliation_agreements_with_ofccp;
    /**
     * @member {String} is_valid
     * @type {String}
     */
    is_valid;
    /**
     * @member {Date} modified
     * @type {Date}
     */
    modified;
    /**
     * @member {String} name
     * @type {String}
     */
    name;
    /**
     * @member {String} past_vendor
     * @type {String}
     */
    past_vendor;
    /**
     * @member {String} postal_code
     * @type {String}
     */
    postal_code;
    /**
     * @member {String} sein
     * @type {String}
     */
    sein;
    /**
     * @member {Company.StatusEnum} status
     * @type {Company.StatusEnum}
     */
    status;
    /**
     * @member {String} street_address
     * @type {String}
     */
    street_address;
    /**
     * @member {String} uiid
     * @type {String}
     */
    uiid;

    

    /**
     * Constructs a new <code>Company</code>.
     * @alias module:model/Company
     * @param ats {ATS} 
     * @param atsCompanyId {String} 
     * @param atsCredentials {Object} 
     * @param contacts {String} 
     * @param postalCode {String} 
     */
    constructor(ats, atsCompanyId, atsCredentials, contacts, postalCode) { 
        
        Company.initialize(this, ats, atsCompanyId, atsCredentials, contacts, postalCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ats, atsCompanyId, atsCredentials, contacts, postalCode) { 
        obj['ats'] = ats;
        obj['ats_company_id'] = atsCompanyId;
        obj['ats_credentials'] = atsCredentials;
        obj['contacts'] = contacts;
        obj['postal_code'] = postalCode;
    }

    /**
     * Constructs a <code>Company</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Company} obj Optional instance to populate.
     * @return {module:model/Company} The populated <code>Company</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Company();

            if (data.hasOwnProperty('ats')) {
                obj['ats'] = ATS.constructFromObject(data['ats']);
            }
            if (data.hasOwnProperty('ats_company_id')) {
                obj['ats_company_id'] = ApiClient.convertToType(data['ats_company_id'], 'String');
            }
            if (data.hasOwnProperty('ats_credentials')) {
                obj['ats_credentials'] = ApiClient.convertToType(data['ats_credentials'], Object);
            }
            if (data.hasOwnProperty('career_site_url')) {
                obj['career_site_url'] = ApiClient.convertToType(data['career_site_url'], 'String');
            }
            if (data.hasOwnProperty('compliance_admin_point_of_contact')) {
                obj['compliance_admin_point_of_contact'] = ApiClient.convertToType(data['compliance_admin_point_of_contact'], 'String');
            }
            if (data.hasOwnProperty('contacts')) {
                obj['contacts'] = ApiClient.convertToType(data['contacts'], ['String']);
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('failed_audit_in_past_3_years')) {
                obj['failed_audit_in_past_3_years'] = ApiClient.convertToType(data['failed_audit_in_past_3_years'], 'Boolean');
            }
            if (data.hasOwnProperty('fein')) {
                obj['fein'] = ApiClient.convertToType(data['fein'], 'String');
            }
            if (data.hasOwnProperty('hr_point_of_contact')) {
                obj['hr_point_of_contact'] = ApiClient.convertToType(data['hr_point_of_contact'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('is_under_conciliation_agreements_with_ofccp')) {
                obj['is_under_conciliation_agreements_with_ofccp'] = ApiClient.convertToType(data['is_under_conciliation_agreements_with_ofccp'], 'Boolean');
            }
            if (data.hasOwnProperty('is_valid')) {
                obj['is_valid'] = ApiClient.convertToType(data['is_valid'], 'String');
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('past_vendor')) {
                obj['past_vendor'] = ApiClient.convertToType(data['past_vendor'], 'String');
            }
            if (data.hasOwnProperty('postal_code')) {
                obj['postal_code'] = ApiClient.convertToType(data['postal_code'], 'String');
            }
            if (data.hasOwnProperty('sein')) {
                obj['sein'] = ApiClient.convertToType(data['sein'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('street_address')) {
                obj['street_address'] = ApiClient.convertToType(data['street_address'], 'String');
            }
            if (data.hasOwnProperty('uiid')) {
                obj['uiid'] = ApiClient.convertToType(data['uiid'], 'String');
            }
        }
        return obj;
    }
}


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Company['StatusEnum'] = {

    /**
     * value: "in_review"
     * @const
     */
    "in_review": "in_review",

    /**
     * value: "active"
     * @const
     */
    "active": "active",

    /**
     * value: "terminated"
     * @const
     */
    "terminated": "terminated"
};



export default Company;

