/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PointOfContact model module.
 * @module model/PointOfContact
 * @version v1
 */
class PointOfContact {
    /**
     * Constructs a new <code>PointOfContact</code>.
     * @alias module:model/PointOfContact
     * @param companies {Array.<String>} 
     */
    constructor(companies) { 
        
        PointOfContact.initialize(this, companies);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, companies) { 
        obj['companies'] = companies;
    }

    /**
     * Constructs a <code>PointOfContact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PointOfContact} obj Optional instance to populate.
     * @return {module:model/PointOfContact} The populated <code>PointOfContact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PointOfContact();

            if (data.hasOwnProperty('companies')) {
                obj['companies'] = ApiClient.convertToType(data['companies'], ['String']);
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('email_address')) {
                obj['email_address'] = ApiClient.convertToType(data['email_address'], 'String');
            }
            if (data.hasOwnProperty('full_name')) {
                obj['full_name'] = ApiClient.convertToType(data['full_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('is_valid')) {
                obj['is_valid'] = ApiClient.convertToType(data['is_valid'], 'Boolean');
            }
            if (data.hasOwnProperty('job_title')) {
                obj['job_title'] = ApiClient.convertToType(data['job_title'], 'String');
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'Date');
            }
            if (data.hasOwnProperty('phone_number')) {
                obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} companies
 */
PointOfContact.prototype['companies'] = undefined;

/**
 * @member {Date} created
 */
PointOfContact.prototype['created'] = undefined;

/**
 * @member {String} email_address
 */
PointOfContact.prototype['email_address'] = undefined;

/**
 * @member {String} full_name
 */
PointOfContact.prototype['full_name'] = undefined;

/**
 * @member {String} id
 */
PointOfContact.prototype['id'] = undefined;

/**
 * @member {Boolean} is_valid
 */
PointOfContact.prototype['is_valid'] = undefined;

/**
 * @member {String} job_title
 */
PointOfContact.prototype['job_title'] = undefined;

/**
 * @member {Date} modified
 */
PointOfContact.prototype['modified'] = undefined;

/**
 * @member {String} phone_number
 */
PointOfContact.prototype['phone_number'] = undefined;






export default PointOfContact;

