/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LiteTransaction from './LiteTransaction';

/**
 * The Vacancy model module.
 * @module model/Vacancy
 * @version v1
 */
class Vacancy {
    /**
     * @member {String} id
     * @type {String}
     */
    id;
    /**
     * @member {Array.<CodegenProperty{openApiType='LiteTransaction', baseName='transactions', complexType='LiteTransaction', getter='getTransactions', setter='setTransactions', description='null', dataType='LiteTransaction', datatypeWithEnum='LiteTransaction', dataFormat='null', name='transactions', min='null', max='null', defaultValue='null', defaultValueWithParam=' = LiteTransaction.constructFromObject(data['transactions']);', baseType='LiteTransaction', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/LiteTransaction"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Transactions', nameInSnakeCase='TRANSACTIONS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false}>} transactions
     * @type {Array.<CodegenProperty{openApiType='LiteTransaction', baseName='transactions', complexType='LiteTransaction', getter='getTransactions', setter='setTransactions', description='null', dataType='LiteTransaction', datatypeWithEnum='LiteTransaction', dataFormat='null', name='transactions', min='null', max='null', defaultValue='null', defaultValueWithParam=' = LiteTransaction.constructFromObject(data['transactions']);', baseType='LiteTransaction', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/LiteTransaction"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Transactions', nameInSnakeCase='TRANSACTIONS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false}>}
     */
    transactions;
    /**
     * @member {String} req_number
     * @type {String}
     */
    req_number;
    /**
     * @member {String} company_name
     * @type {String}
     */
    company_name;
    /**
     * @member {String} job_location
     * @type {String}
     */
    job_location;
    /**
     * @member {Vacancy.StateEnum} state
     * @type {Vacancy.StateEnum}
     */
    state;
    /**
     * @member {String} job_title
     * @type {String}
     */
    job_title;
    /**
     * @member {String} apply_url
     * @type {String}
     */
    apply_url;
    /**
     * @member {String} company
     * @type {String}
     */
    company;

    

    /**
     * Constructs a new <code>Vacancy</code>.
     * @alias module:model/Vacancy
     * @param transactions {Array.<CodegenProperty{openApiType='LiteTransaction', baseName='transactions', complexType='LiteTransaction', getter='getTransactions', setter='setTransactions', description='null', dataType='LiteTransaction', datatypeWithEnum='LiteTransaction', dataFormat='null', name='transactions', min='null', max='null', defaultValue='null', defaultValueWithParam=' = LiteTransaction.constructFromObject(data['transactions']);', baseType='LiteTransaction', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/LiteTransaction"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isShort=false, isLong=false, isUnboundedInteger=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isAnyType=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Transactions', nameInSnakeCase='TRANSACTIONS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false, isNull=false, getAdditionalPropertiesIsAnyType=false, getHasVars=false, getHasRequired=false, getHasDiscriminatorWithNonEmptyMapping=false, composedSchemas=null, hasMultipleTypes=false}>} 
     * @param reqNumber {String} 
     * @param companyName {String} 
     * @param jobLocation {String} 
     * @param jobTitle {String} 
     * @param applyUrl {String} 
     * @param company {String} 
     */
    constructor(transactions, reqNumber, companyName, jobLocation, jobTitle, applyUrl, company) { 
        
        Vacancy.initialize(this, transactions, reqNumber, companyName, jobLocation, jobTitle, applyUrl, company);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transactions, reqNumber, companyName, jobLocation, jobTitle, applyUrl, company) { 
        obj['transactions'] = transactions;
        obj['req_number'] = reqNumber;
        obj['company_name'] = companyName;
        obj['job_location'] = jobLocation;
        obj['job_title'] = jobTitle;
        obj['apply_url'] = applyUrl;
        obj['company'] = company;
    }

    /**
     * Constructs a <code>Vacancy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Vacancy} obj Optional instance to populate.
     * @return {module:model/Vacancy} The populated <code>Vacancy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Vacancy();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('transactions')) {
                obj['transactions'] = ApiClient.convertToType(data['transactions'], [LiteTransaction]);
            }
            if (data.hasOwnProperty('req_number')) {
                obj['req_number'] = ApiClient.convertToType(data['req_number'], 'String');
            }
            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('job_location')) {
                obj['job_location'] = ApiClient.convertToType(data['job_location'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('job_title')) {
                obj['job_title'] = ApiClient.convertToType(data['job_title'], 'String');
            }
            if (data.hasOwnProperty('apply_url')) {
                obj['apply_url'] = ApiClient.convertToType(data['apply_url'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
        }
        return obj;
    }
}


/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
Vacancy['StateEnum'] = {

    /**
     * value: "AL"
     * @const
     */
    "AL": "AL",

    /**
     * value: "AK"
     * @const
     */
    "AK": "AK",

    /**
     * value: "AS"
     * @const
     */
    "AS": "AS",

    /**
     * value: "AZ"
     * @const
     */
    "AZ": "AZ",

    /**
     * value: "AR"
     * @const
     */
    "AR": "AR",

    /**
     * value: "AA"
     * @const
     */
    "AA": "AA",

    /**
     * value: "AE"
     * @const
     */
    "AE": "AE",

    /**
     * value: "AP"
     * @const
     */
    "AP": "AP",

    /**
     * value: "CA"
     * @const
     */
    "CA": "CA",

    /**
     * value: "CO"
     * @const
     */
    "CO": "CO",

    /**
     * value: "CT"
     * @const
     */
    "CT": "CT",

    /**
     * value: "DE"
     * @const
     */
    "DE": "DE",

    /**
     * value: "DC"
     * @const
     */
    "DC": "DC",

    /**
     * value: "FL"
     * @const
     */
    "FL": "FL",

    /**
     * value: "GA"
     * @const
     */
    "GA": "GA",

    /**
     * value: "GU"
     * @const
     */
    "GU": "GU",

    /**
     * value: "HI"
     * @const
     */
    "HI": "HI",

    /**
     * value: "ID"
     * @const
     */
    "ID": "ID",

    /**
     * value: "IL"
     * @const
     */
    "IL": "IL",

    /**
     * value: "IN"
     * @const
     */
    "IN": "IN",

    /**
     * value: "IA"
     * @const
     */
    "IA": "IA",

    /**
     * value: "KS"
     * @const
     */
    "KS": "KS",

    /**
     * value: "KY"
     * @const
     */
    "KY": "KY",

    /**
     * value: "LA"
     * @const
     */
    "LA": "LA",

    /**
     * value: "ME"
     * @const
     */
    "ME": "ME",

    /**
     * value: "MD"
     * @const
     */
    "MD": "MD",

    /**
     * value: "MA"
     * @const
     */
    "MA": "MA",

    /**
     * value: "MI"
     * @const
     */
    "MI": "MI",

    /**
     * value: "MN"
     * @const
     */
    "MN": "MN",

    /**
     * value: "MS"
     * @const
     */
    "MS": "MS",

    /**
     * value: "MO"
     * @const
     */
    "MO": "MO",

    /**
     * value: "MT"
     * @const
     */
    "MT": "MT",

    /**
     * value: "NE"
     * @const
     */
    "NE": "NE",

    /**
     * value: "NV"
     * @const
     */
    "NV": "NV",

    /**
     * value: "NH"
     * @const
     */
    "NH": "NH",

    /**
     * value: "NJ"
     * @const
     */
    "NJ": "NJ",

    /**
     * value: "NM"
     * @const
     */
    "NM": "NM",

    /**
     * value: "NY"
     * @const
     */
    "NY": "NY",

    /**
     * value: "NC"
     * @const
     */
    "NC": "NC",

    /**
     * value: "ND"
     * @const
     */
    "ND": "ND",

    /**
     * value: "MP"
     * @const
     */
    "MP": "MP",

    /**
     * value: "OH"
     * @const
     */
    "OH": "OH",

    /**
     * value: "OK"
     * @const
     */
    "OK": "OK",

    /**
     * value: "OR"
     * @const
     */
    "OR": "OR",

    /**
     * value: "PA"
     * @const
     */
    "PA": "PA",

    /**
     * value: "PR"
     * @const
     */
    "PR": "PR",

    /**
     * value: "RI"
     * @const
     */
    "RI": "RI",

    /**
     * value: "SC"
     * @const
     */
    "SC": "SC",

    /**
     * value: "SD"
     * @const
     */
    "SD": "SD",

    /**
     * value: "TN"
     * @const
     */
    "TN": "TN",

    /**
     * value: "TX"
     * @const
     */
    "TX": "TX",

    /**
     * value: "UT"
     * @const
     */
    "UT": "UT",

    /**
     * value: "VT"
     * @const
     */
    "VT": "VT",

    /**
     * value: "VI"
     * @const
     */
    "VI": "VI",

    /**
     * value: "VA"
     * @const
     */
    "VA": "VA",

    /**
     * value: "WA"
     * @const
     */
    "WA": "WA",

    /**
     * value: "WV"
     * @const
     */
    "WV": "WV",

    /**
     * value: "WI"
     * @const
     */
    "WI": "WI",

    /**
     * value: "WY"
     * @const
     */
    "WY": "WY"
};



export default Vacancy;

