/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */



import ApiClient from "../ApiClient";

/**
* GetEnvelopeStatus service.
* @module api/GetEnvelopeStatusApi
* @version v1
*/
export default class GetEnvelopeStatusApi extends ApiClient {

    /**
    * Constructs a new GetEnvelopeStatusApi. 
    * @alias module:api/GetEnvelopeStatusApi
    * @class
    */
    constructor() {
      super();
      this.baseURL = null;
    }


    /**
     * @param {String} envelopeId 
     * @return {Promise}
     */
    async getEnvelopeStatusRead(envelopeId) {
      let postBody = null;
      // verify the required parameter 'envelopeId' is set
      if (envelopeId === undefined || envelopeId === null) {
        throw new Error("Missing the required parameter 'envelopeId' when calling getEnvelopeStatusRead");
      }

      let pathParams = {
        'envelope_id': envelopeId
      };
      let queryParams = {
      };
      let headerParams = {
        'User-Agent': 'OpenAPI-Generator/v1/Javascript',
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.callApi(
        '/get_envelope_status/{envelope_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }


}
