/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* GetEnvelopeStatus service.
* @module api/GetEnvelopeStatusApi
* @version v1
*/
export default class GetEnvelopeStatusApi {

    /**
    * Constructs a new GetEnvelopeStatusApi. 
    * @alias module:api/GetEnvelopeStatusApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getEnvelopeStatusRead operation.
     * @callback module:api/GetEnvelopeStatusApi~getEnvelopeStatusReadCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} envelopeId 
     * @param {module:api/GetEnvelopeStatusApi~getEnvelopeStatusReadCallback} callback The callback function, accepting three arguments: error, data, response
     */
    getEnvelopeStatusRead(envelopeId, callback) {
      let postBody = null;
      // verify the required parameter 'envelopeId' is set
      if (envelopeId === undefined || envelopeId === null) {
        throw new Error("Missing the required parameter 'envelopeId' when calling getEnvelopeStatusRead");
      }

      let pathParams = {
        'envelope_id': envelopeId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/get_envelope_status/{envelope_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
