/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BoardPublic from '../model/BoardPublic';

/**
* Jobboardbystate service.
* @module api/JobboardbystateApi
* @version v1
*/
export default class JobboardbystateApi {

    /**
    * Constructs a new JobboardbystateApi. 
    * @alias module:api/JobboardbystateApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the listJobBoardByStateCode operation.
     * @callback module:api/JobboardbystateApi~listJobBoardByStateCodeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BoardPublic} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List job board by state code, including credentials schema
     *  This endpoint lists the job board used for a given state including the schema for the required credentials. This endpoint is to be used to render the  jobboard credentials onboarding form 
     * @param {String} stateCode 
     * @param {module:model/String} stateCode2 
     * @param {module:api/JobboardbystateApi~listJobBoardByStateCodeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BoardPublic}
     */
    listJobBoardByStateCode(stateCode, stateCode2, callback) {
      let postBody = null;
      // verify the required parameter 'stateCode' is set
      if (stateCode === undefined || stateCode === null) {
        throw new Error("Missing the required parameter 'stateCode' when calling listJobBoardByStateCode");
      }
      // verify the required parameter 'stateCode2' is set
      if (stateCode2 === undefined || stateCode2 === null) {
        throw new Error("Missing the required parameter 'stateCode2' when calling listJobBoardByStateCode");
      }

      let pathParams = {
        'state_code': stateCode
      };
      let queryParams = {
        'state_code': stateCode2
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BoardPublic;
      return this.apiClient.callApi(
        '/jobboards/{state_code}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
