/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */



import ApiClient from "../ApiClient";
import BoardPublic from '../model/BoardPublic';

/**
* Jobboardbystate service.
* @module api/JobboardbystateApi
* @version v1
*/
export default class JobboardbystateApi extends ApiClient {

    /**
    * Constructs a new JobboardbystateApi. 
    * @alias module:api/JobboardbystateApi
    * @class
    */
    constructor() {
      super();
      this.baseURL = null;
    }


    /**
     * List job board by state code, including credentials schema
     *  This endpoint lists the job board used for a given state including the schema for the required credentials. This endpoint is to be used to render the  jobboard credentials onboarding form 
     * @param {String} stateCode 
     * @param {String} stateCode2 
     * @return {Promise<BoardPublic>}
     */
    async listJobBoardByStateCode(stateCode, stateCode2) {
      let postBody = null;
      // verify the required parameter 'stateCode' is set
      if (stateCode === undefined || stateCode === null) {
        throw new Error("Missing the required parameter 'stateCode' when calling listJobBoardByStateCode");
      }
      // verify the required parameter 'stateCode2' is set
      if (stateCode2 === undefined || stateCode2 === null) {
        throw new Error("Missing the required parameter 'stateCode2' when calling listJobBoardByStateCode");
      }

      let pathParams = {
        'state_code': stateCode
      };
      let queryParams = {
        'state_code': stateCode2
      };
      let headerParams = {
        'User-Agent': 'OpenAPI-Generator/v1/Javascript',
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BoardPublic;

      return this.callApi(
        '/jobboards/{state_code}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }


}
