/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */



import ApiClient from "../ApiClient";
import Tier from '../model/Tier';

/**
* Tiers service.
* @module api/TiersApi
* @version v1
*/
export default class TiersApi extends ApiClient {

    /**
    * Constructs a new TiersApi. 
    * @alias module:api/TiersApi
    * @class
    */
    constructor() {
      super();
      this.baseURL = null;
    }


    /**
     * @return {Promise<Array.<Tier>>}
     */
    async tiersList() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'User-Agent': 'OpenAPI-Generator/v1/Javascript',
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Tier];

      return this.callApi(
        '/tiers/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }


}
