/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HapiOnboardingApi);
  }
}(this, function(expect, HapiOnboardingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HapiOnboardingApi.BoardContract();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BoardContract', function() {
    it('should create an instance of BoardContract', function() {
      // uncomment below and update the code to test BoardContract
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be.a(HapiOnboardingApi.BoardContract);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be();
    });

    it('should have the property jobboardCode (base name: "jobboard_code")', function() {
      // uncomment below and update the code to test the property jobboardCode
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be();
    });

    it('should have the property isValid (base name: "is_valid")', function() {
      // uncomment below and update the code to test the property isValid
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be();
    });

    it('should have the property modified (base name: "modified")', function() {
      // uncomment below and update the code to test the property modified
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be();
    });

    it('should have the property credentials (base name: "credentials")', function() {
      // uncomment below and update the code to test the property credentials
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be();
    });

    it('should have the property companySubsidiary (base name: "company_subsidiary")', function() {
      // uncomment below and update the code to test the property companySubsidiary
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new HapiOnboardingApi.BoardContract();
      //expect(instance).to.be();
    });

  });

}));
