/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HapiOnboardingApi);
  }
}(this, function(expect, HapiOnboardingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HapiOnboardingApi.CompanySubsidiary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompanySubsidiary', function() {
    it('should create an instance of CompanySubsidiary', function() {
      // uncomment below and update the code to test CompanySubsidiary
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be.a(HapiOnboardingApi.CompanySubsidiary);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property valid (base name: "valid")', function() {
      // uncomment below and update the code to test the property valid
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property modified (base name: "modified")', function() {
      // uncomment below and update the code to test the property modified
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property atsCompanyId (base name: "ats_company_id")', function() {
      // uncomment below and update the code to test the property atsCompanyId
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property atsCredentials (base name: "ats_credentials")', function() {
      // uncomment below and update the code to test the property atsCredentials
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property streetAddress (base name: "street_address")', function() {
      // uncomment below and update the code to test the property streetAddress
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postal_code")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property careerSiteUrl (base name: "career_site_url")', function() {
      // uncomment below and update the code to test the property careerSiteUrl
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property fein (base name: "fein")', function() {
      // uncomment below and update the code to test the property fein
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property sein (base name: "sein")', function() {
      // uncomment below and update the code to test the property sein
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property uiid (base name: "uiid")', function() {
      // uncomment below and update the code to test the property uiid
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property letterOfAuthDocusignEnvelope (base name: "letter_of_auth_docusign_envelope")', function() {
      // uncomment below and update the code to test the property letterOfAuthDocusignEnvelope
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property ats (base name: "ats")', function() {
      // uncomment below and update the code to test the property ats
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property hrPointOfContact (base name: "hr_point_of_contact")', function() {
      // uncomment below and update the code to test the property hrPointOfContact
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property complianceAdminPointOfContact (base name: "compliance_admin_point_of_contact")', function() {
      // uncomment below and update the code to test the property complianceAdminPointOfContact
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new HapiOnboardingApi.CompanySubsidiary();
      //expect(instance).to.be();
    });

  });

}));
