/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HapiOnboardingApi);
  }
}(this, function(expect, HapiOnboardingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HapiOnboardingApi.PointOfContact();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PointOfContact', function() {
    it('should create an instance of PointOfContact', function() {
      // uncomment below and update the code to test PointOfContact
      //var instance = new HapiOnboardingApi.PointOfContact();
      //expect(instance).to.be.a(HapiOnboardingApi.PointOfContact);
    });

    it('should have the property companies (base name: "companies")', function() {
      // uncomment below and update the code to test the property companies
      //var instance = new HapiOnboardingApi.PointOfContact();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new HapiOnboardingApi.PointOfContact();
      //expect(instance).to.be();
    });

    it('should have the property emailAddress (base name: "email_address")', function() {
      // uncomment below and update the code to test the property emailAddress
      //var instance = new HapiOnboardingApi.PointOfContact();
      //expect(instance).to.be();
    });

    it('should have the property fullName (base name: "full_name")', function() {
      // uncomment below and update the code to test the property fullName
      //var instance = new HapiOnboardingApi.PointOfContact();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HapiOnboardingApi.PointOfContact();
      //expect(instance).to.be();
    });

    it('should have the property isValid (base name: "is_valid")', function() {
      // uncomment below and update the code to test the property isValid
      //var instance = new HapiOnboardingApi.PointOfContact();
      //expect(instance).to.be();
    });

    it('should have the property jobTitle (base name: "job_title")', function() {
      // uncomment below and update the code to test the property jobTitle
      //var instance = new HapiOnboardingApi.PointOfContact();
      //expect(instance).to.be();
    });

    it('should have the property modified (base name: "modified")', function() {
      // uncomment below and update the code to test the property modified
      //var instance = new HapiOnboardingApi.PointOfContact();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "phone_number")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instance = new HapiOnboardingApi.PointOfContact();
      //expect(instance).to.be();
    });

  });

}));
