/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HapiOnboardingApi);
  }
}(this, function(expect, HapiOnboardingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HapiOnboardingApi.Tier();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Tier', function() {
    it('should create an instance of Tier', function() {
      // uncomment below and update the code to test Tier
      //var instance = new HapiOnboardingApi.Tier();
      //expect(instance).to.be.a(HapiOnboardingApi.Tier);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HapiOnboardingApi.Tier();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new HapiOnboardingApi.Tier();
      //expect(instance).to.be();
    });

    it('should have the property maximumVacanciesPerYear (base name: "maximum_vacancies_per_year")', function() {
      // uncomment below and update the code to test the property maximumVacanciesPerYear
      //var instance = new HapiOnboardingApi.Tier();
      //expect(instance).to.be();
    });

    it('should have the property deactivationLimit (base name: "deactivation_limit")', function() {
      // uncomment below and update the code to test the property deactivationLimit
      //var instance = new HapiOnboardingApi.Tier();
      //expect(instance).to.be();
    });

    it('should have the property vonqPrice (base name: "vonq_price")', function() {
      // uncomment below and update the code to test the property vonqPrice
      //var instance = new HapiOnboardingApi.Tier();
      //expect(instance).to.be();
    });

    it('should have the property rateCardPrice (base name: "rate_card_price")', function() {
      // uncomment below and update the code to test the property rateCardPrice
      //var instance = new HapiOnboardingApi.Tier();
      //expect(instance).to.be();
    });

  });

}));
