/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HapiOnboardingApi);
  }
}(this, function(expect, HapiOnboardingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HapiOnboardingApi.Transaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Transaction', function() {
    it('should create an instance of Transaction', function() {
      // uncomment below and update the code to test Transaction
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be.a(HapiOnboardingApi.Transaction);
    });

    it('should have the property applyUrl (base name: "apply_url")', function() {
      // uncomment below and update the code to test the property applyUrl
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property atsCompanyId (base name: "ats_company_id")', function() {
      // uncomment below and update the code to test the property atsCompanyId
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property atsId (base name: "ats_id")', function() {
      // uncomment below and update the code to test the property atsId
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property channel (base name: "channel")', function() {
      // uncomment below and update the code to test the property channel
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "company_name")', function() {
      // uncomment below and update the code to test the property companyName
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property confirmationId (base name: "confirmation_id")', function() {
      // uncomment below and update the code to test the property confirmationId
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property distributionType (base name: "distribution_type")', function() {
      // uncomment below and update the code to test the property distributionType
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property jobLocation (base name: "job_location")', function() {
      // uncomment below and update the code to test the property jobLocation
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property jobTitle (base name: "job_title")', function() {
      // uncomment below and update the code to test the property jobTitle
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property outreachCentreEmailAddress (base name: "outreach_centre_email_address")', function() {
      // uncomment below and update the code to test the property outreachCentreEmailAddress
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property postingTimestamp (base name: "posting_timestamp")', function() {
      // uncomment below and update the code to test the property postingTimestamp
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property publicationUrl (base name: "publication_url")', function() {
      // uncomment below and update the code to test the property publicationUrl
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property reqNumber (base name: "req_number")', function() {
      // uncomment below and update the code to test the property reqNumber
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionId (base name: "transaction_id")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionMethod (base name: "transaction_method")', function() {
      // uncomment below and update the code to test the property transactionMethod
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionTimestamp (base name: "transaction_timestamp")', function() {
      // uncomment below and update the code to test the property transactionTimestamp
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionType (base name: "transaction_type")', function() {
      // uncomment below and update the code to test the property transactionType
      //var instance = new HapiOnboardingApi.Transaction();
      //expect(instance).to.be();
    });

  });

}));
