/**
 * HAPI Onboarding API
 * Simple API for handling employer onboarding
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ATS from './model/ATS';
import BoardContract from './model/BoardContract';
import BoardPublic from './model/BoardPublic';
import Company from './model/Company';
import CompanySubsidiary from './model/CompanySubsidiary';
import LiteTransaction from './model/LiteTransaction';
import PointOfContact from './model/PointOfContact';
import Tier from './model/Tier';
import Transaction from './model/Transaction';
import Vacancy from './model/Vacancy';
import CompaniesApi from './api/CompaniesApi';
import GetEnvelopeStatusApi from './api/GetEnvelopeStatusApi';
import JobboardbystateApi from './api/JobboardbystateApi';
import TiersApi from './api/TiersApi';
import TransactionsApi from './api/TransactionsApi';
import VacanciesApi from './api/VacanciesApi';


/**
* Simple_API_for_handling_employer_onboarding.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var HapiOnboardingApi = require('index'); // See note below*.
* var xxxSvc = new HapiOnboardingApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new HapiOnboardingApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new HapiOnboardingApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new HapiOnboardingApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ATS model constructor.
     * @property {module:model/ATS}
     */
    ATS,

    /**
     * The BoardContract model constructor.
     * @property {module:model/BoardContract}
     */
    BoardContract,

    /**
     * The BoardPublic model constructor.
     * @property {module:model/BoardPublic}
     */
    BoardPublic,

    /**
     * The Company model constructor.
     * @property {module:model/Company}
     */
    Company,

    /**
     * The CompanySubsidiary model constructor.
     * @property {module:model/CompanySubsidiary}
     */
    CompanySubsidiary,

    /**
     * The LiteTransaction model constructor.
     * @property {module:model/LiteTransaction}
     */
    LiteTransaction,

    /**
     * The PointOfContact model constructor.
     * @property {module:model/PointOfContact}
     */
    PointOfContact,

    /**
     * The Tier model constructor.
     * @property {module:model/Tier}
     */
    Tier,

    /**
     * The Transaction model constructor.
     * @property {module:model/Transaction}
     */
    Transaction,

    /**
     * The Vacancy model constructor.
     * @property {module:model/Vacancy}
     */
    Vacancy,

    /**
    * The CompaniesApi service constructor.
    * @property {module:api/CompaniesApi}
    */
    CompaniesApi,

    /**
    * The GetEnvelopeStatusApi service constructor.
    * @property {module:api/GetEnvelopeStatusApi}
    */
    GetEnvelopeStatusApi,

    /**
    * The JobboardbystateApi service constructor.
    * @property {module:api/JobboardbystateApi}
    */
    JobboardbystateApi,

    /**
    * The TiersApi service constructor.
    * @property {module:api/TiersApi}
    */
    TiersApi,

    /**
    * The TransactionsApi service constructor.
    * @property {module:api/TransactionsApi}
    */
    TransactionsApi,

    /**
    * The VacanciesApi service constructor.
    * @property {module:api/VacanciesApi}
    */
    VacanciesApi
};
